import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// import Link from 'next/link';
// import './globals.css';

// export const metadata = {
//   title: 'My Next.js App',
//   description: 'Generated by Next.js',
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <header className="header">
//           <nav className="nav">
//             <Link href="/">Home</Link>
//             <Link href="/about">About</Link>
//             {/* <Link href="/box1">Box</Link> */}
//           </nav>
//         </header>
//         <main>{children}</main>
//         <footer className="footer">
//           <p>Footer content here</p>
//         </footer>
//       </body>
//     </html>
//   );
// }
